language: php
php:
  - 8.1
env:
  - APP_ENV=test
before_script: 
  - composer install -o -n
  - php bin/console doctrine:database:create && php bin/console doctrine:schema:create && php bin/console doctrine:fixtures:load --no-interaction
script: php bin/phpunit --testdox
