version: '3.5'

services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    depends_on:
      - postgres
    networks: 
      webnet:
        aliases:
          - web

###> doctrine/doctrine-bundle ###
  postgres:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      webnet:
        aliases:
          - postgres
          - postgres-server
###< doctrine/doctrine-bundle ###

networks:
  webnet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
